### ISSUE TITLE
DataBufferLimitException at querying pokemon mew

### ISSUE THREAD

**Issue by joshi1999** [SirSkaro/pokeapi-reactor#6]
Querying Mew results in a DataBufferLimitException.

`Caused by: org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 550000`

It's set here: https://github.com/SirSkaro/pokeapi-reactor/blob/master/src/main/java/skaro/pokeapi/PokeApiReactorBaseConfiguration.java#L39

Is there a legal way to modify this limit, or do I have to recompile the source my self?

**Comment by SirSkaro** [comment]
I ran into that same problem when querying `/pokemon/mew` during development and upped the buffer to 550k from the default size. But I guess Mew has even more data now. I really should have made that buffer limit an externalized configuration. 

If you like you can create a pull request to set the max buffer size in [PokeApiConfigurationProperties](https://github.com/SirSkaro/pokeapi-reactor/blob/846f45d4e38967efb37ea5d5a9a28da557d4072a/src/main/java/skaro/pokeapi/PokeApiConfigurationProperties.java) (via a `.properties`/`.yaml` file) with a default value that handles the `/pokemon/mew` resource. Otherwise I probably won't get around to this until some time in May.

**Comment by SirSkaro** [comment]
Created [a package ](https://github.com/SirSkaro/pokeapi-reactor/packages/1173543) for version `1.0.6` that includes your PR. Just need to update your dependency and you're good to go! Thanks again for contributing!
